apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable

patches:
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
