apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.chik4ge.me
  admin.enabled: "false"
  
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23liO6LEyYow0nlys8
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: chik4ge-homelab
  
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"

  resource.compareoptions: |
    ignoreResourceStatusField: crd
